#ifndef CERTIFICATE_SERVER_ERROR_HPP
#define CERTIFICATE_SERVER_ERROR_HPP

enum error_code{
    ERR_RSA_GEN = 1,
    ERR_FILE_NOT_FOUND = 2,
    ERR_BAD_ARG = 3,
    ERR_SIGN_FAIL = 4,
    ERR_CERT_GEN = 5,
    ERR_PEM_CONVERT = 6,
    ERR_PEM_LOAD = 7,
    ERR_SERV_START = 8
};

#endif //CERTIFICATE_SERVER_ERROR_HPP
